apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: default
  labels:
    app: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: ghcr.io/vkctl/vote:dev-latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              cpu: 250m
              memory: 400Mi
---
apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: default
  labels:
    app: vote
spec:
  type: LoadBalancer
  selector:
    app: vote
  ports:
    - port: 80
      targetPort: 80
